# This workflow builds the Python package, and uploads to PyPI using Twine

name: Build & upload to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Make manylinux wheels
        env:
          target: manylinux2014_x86_64
        run: |
          docker run -e PLAT=${{ env.target }} \
            -v ${{ github.workspace }}:/io \
            quay.io/pypa/${{ env.target }} \
            /io/.github/build-manylinux-wheels
      - name: Install wheel publishing deps
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade twine
      - env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m twine upload ./dist/*manylinux* ./dist/*.tar.gz
